# Generated by Django 4.0.6 on 2022-07-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='review',
            name='review_limit',
            field=models.IntegerField(default=0),
        ),
    ]
