# Generated by Django 4.0.6 on 2022-07-04 22:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartitem',
            managers=[
                ('ecommerce', django.db.models.manager.Manager()),
            ],
        ),
    ]
