# Generated by Django 4.0.6 on 2022-07-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='images_category',
        ),
    ]
