# Generated by Django 4.0.5 on 2022-07-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
