# Generated by Django 4.0.5 on 2022-07-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='vistors',
            field=models.IntegerField(default=0),
        ),
    ]
