# Generated by Django 4.0.5 on 2022-07-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_alter_product_product_price_alter_user_cup_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='checked_cart_item',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='cart_item_quntity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='checked_cart_item',
            name='checked_cart_item_quntity',
            field=models.IntegerField(default=1),
        ),
    ]
