# Generated by Django 4.0.5 on 2022-06-19 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_first_name', models.CharField(max_length=50)),
                ('Cart_last_name', models.CharField(max_length=50)),
                ('Cart_email', models.EmailField(max_length=255, unique=True)),
                ('Cart_mobile', models.CharField(max_length=15)),
                ('Cart_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Cart_shipping', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Cart_grand_total', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_item_title', models.CharField(max_length=75)),
                ('Cart_item_photo', models.ImageField(upload_to='')),
                ('Cart_item_size', models.CharField(max_length=7)),
                ('Cart_item_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Cart_item_quntity', models.IntegerField()),
                ('Cart_item_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_commerce.images')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='Order_user',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='Order_item_order',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='Order_item_product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Transaction_order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Transaction_user',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='Category_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='gender',
            new_name='Category_gender',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='is_active',
            new_name='Category_is_active',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='Category_title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Product_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='details',
            new_name='Product_details',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='Product_discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='Product_is_active',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Product_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='Product_title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='Product_user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='Review_content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='Review_product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='Review_rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='Review_user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='size',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_brand',
            field=models.CharField(default='Null', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='size_name',
            field=models.CharField(default='Null', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='size_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Null', max_length=75),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_item',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='Cart_item_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_commerce.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Cart_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_product',
            field=models.ManyToManyField(to='e_commerce.cart_item'),
        ),
    ]
