# Generated by Django 4.0.6 on 2022-07-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_remove_image_images_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedcartitem',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.product'),
        ),
    ]
