# Generated by Django 4.0.5 on 2022-06-11 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_remove_images_images_physical_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='product',
        ),
        migrations.AddField(
            model_name='address',
            name='Address_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='product_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
