# Generated by Django 4.0.5 on 2022-06-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_cart_cart_item_remove_order_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='Color_product',
        ),
        migrations.RemoveField(
            model_name='size',
            name='Size_product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.ManyToManyField(to='e_commerce.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(to='e_commerce.size'),
        ),
    ]
