# Generated by Django 4.0.6 on 2022-07-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_alter_checkedcartitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.CharField(default='NotCode', max_length=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='promo_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_model',
            field=models.TextField(blank=True, null=True),
        ),
    ]
