# Generated by Django 4.0.5 on 2022-06-26 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_remove_color_color_product_remove_size_size_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
