# Generated by Django 4.0.3 on 2022-05-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0007_rename_transaction_code_transaction_transaction_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='User_intro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='User_profile',
        ),
        migrations.AddField(
            model_name='user',
            name='User_admin',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='User_salt',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='User_vendor',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='User_gender',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='User_account',
        ),
    ]
