# Generated by Django 4.0.3 on 2022-05-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0010_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_password',
            field=models.CharField(max_length=300),
        ),
    ]
